CREATE TABLE VEM_SER.PAIS (
	ID_PAIS NUMBER (38,0) NOT NULL,
	NOME VARCHAR2 (50) NOT NULL,
	
	CONSTRAINT PK_ID_PAIS PRIMARY KEY (ID_PAIS)
);

CREATE TABLE VEM_SER.ESTADO (
	ID_ESTADO NUMBER (38,0) NOT NULL,
	ID_PAIS NUMBER (38,0) NOT NULL,
	NOME VARCHAR2 (50) NOT NULL,
	
	CONSTRAINT PK_ID_ESTADO PRIMARY KEY (ID_ESTADO),
	CONSTRAINT FK_ID_PAIS FOREIGN KEY (ID_PAIS) REFERENCES VEM_SER.PAIS (ID_PAIS)
);

CREATE TABLE VEM_SER.CIDADE (
	ID_CIDADE NUMBER (38,0) NOT NULL,
	ID_ESTADO NUMBER (38,0) NOT NULL,
	NOME VARCHAR2 (50) NOT NULL,
	
	CONSTRAINT PK_ID_CIDADE_ESTADO PRIMARY KEY (ID_CIDADE, ID_ESTADO),
	CONSTRAINT FK_ID_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES VEM_SER.ESTADO (ID_ESTADO)
);

CREATE TABLE VEM_SER.BAIRRO (
	ID_BAIRRO NUMBER (38,0) NOT NULL,
	ID_CIDADE NUMBER (38,0) NOT NULL,
	ID_ESTADO NUMBER (38,0) NOT NULL,
	NOME VARCHAR2 (50) NOT NULL,
	
	CONSTRAINT PK_ID_BAIRRO_CIDADE PRIMARY KEY (ID_BAIRRO, ID_CIDADE),
	CONSTRAINT FK_ID_CIDADE_ESTADO FOREIGN KEY (ID_CIDADE, ID_ESTADO) REFERENCES VEM_SER.CIDADE (ID_CIDADE, ID_ESTADO)
);

CREATE TABLE VEM_SER.ENDERECO (
	ID_ENDERECO NUMBER (38,0) NOT NULL,
	ID_BAIRRO NUMBER (38,0) NOT NULL,
	ID_CIDADE  NUMBER (38,0) NOT NULL,
	LOGRADOURO VARCHAR2 (255) NOT NULL,
	NUMERO NUMBER (38,0) NOT NULL,
	COMPLEMENTO VARCHAR2 (100) NOT NULL,
	CEP VARCHAR2 (9) NOT NULL,
	
	CONSTRAINT PK_ID_ENDERECO PRIMARY KEY (ID_ENDERECO),
	CONSTRAINT FK_ID_BAIRRO_CIDADE FOREIGN KEY (ID_BAIRRO, ID_CIDADE) REFERENCES VEM_SER.BAIRRO (ID_BAIRRO, ID_CIDADE)
);

--SEQUENCES

CREATE SEQUENCE SEQ_PAIS
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ESTADO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CIDADE
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_BAIRRO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ENDERECO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

--INSERTS

INSERT INTO VEM_SER.PAIS VALUES (VEM_SER.SEQ_PAIS.nextval,'Brasil');








